### ISSUE TITLE
Modify "%" command string?

### ISSUE THREAD

**Issue by StarlightDaemon** [BiglySoftware/BiglyBT-plugin-azexec#1]
I use the command runner plugin to push notifications with the PushBullet API.  The API for Pushbullet doesn't not like the percent sign "%" used to pass more info from Command runner.  

In this case looking to pass %N or command_n to a push notification, but that results in a error in the Pushbullet API.  Is their a simple way to get that info without using the percent sign? or can the plugin be modified to use a different sign.. possible even a non sign command?

**Comment by parg** [comment]
The %N is supposed to have been replaced with the download name before the command is invoked so I'm not sure why their API would see it...

**Comment by StarlightDaemon** [comment]
100% over looked that, I was testing by passing the command from a BAT file from the remote machine.  @parg Truly a hero of the people!

**Comment by parg** [comment]
\o/
