### ISSUE TITLE
Command runner not running batch file

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT-plugin-azexec#2]
Hi,

I've been using command runner for a very long time (a couple of years or more) but my BiglyBT didn't update automatically so recently I deleted BiglyBT and reinstalled it from scratch in the hope that doing so would fix the update issue.

After installing BiglyBT from scratch I added Command Runner and added the command that was in there previously. This was preserved and then copy and pasted so there's no chance of human error, it's the identical string from the previous install.

However, after all that, Command Runner no longer runs my batch file, or at least it seems that way. Here is the command:

`/home/reg/Libraries/Multimedia/copy-shows.sh "%D/%F"`

I did the normal checks like making sure the batch file is still there and that it works if I pass a string that the `"%D/%F"` represents and it still works. My system is OpenSUSE Leap 15.3.

**Comment by RegProctor** [comment]
I just saw something so I'm going to close this and if it still has a problem I'll open a ticket again.

**Comment by parg** [comment]
OK :)
